"""empty message

Revision ID: 84da56e4c7c2
Revises: 44985b610c41
Create Date: 2020-06-02 15:21:51.710411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84da56e4c7c2'
down_revision = '44985b610c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'questions', ['question_id'], ['id'])
    op.drop_column('options', 'questionaire_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('questionaire_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'questionaires', ['questionaire_id'], ['id'])
    op.drop_column('options', 'question_id')
    # ### end Alembic commands ###
